[settings]
timeout = 180

[ids]
*

[main]
a = overload(meta, a)
s = overload(alt, s)
d = overload(shift, d)
f = overload(control, f)
j = overload(control, j)
k = overload(shift, k)
l = overload(alt, l)
; = overload(meta, ;)

capslock = overload(movement, esc)
rightalt = layer(function)

[movement]
h = left
j = down
k = up
l = right
y = home
u = pagedown
i = pageup
o = end

[function]
h = prev
j = playpause
k = next
