[settings]
timeout = 180

[ids]
*

[main]
a = lettermod(meta, a, 150, 180)
s = lettermod(alt, s, 150, 180)
d = lettermod(shift, d, 150, 180)
f = lettermod(control, f, 150, 180)
j = lettermod(control, j, 150, 180)
k = lettermod(shift, k, 150, 180)
l = lettermod(alt, l, 150, 180)
; = lettermod(meta, ;, 150, 180)

capslock = overload(movement, esc)

[movement]
h = left
j = down
k = up
l = right
