[settings]
timeout = 180

[ids]
*

[main]
a = overload(meta, a)
o = overload(meta, o)

r = overload(alt, r)
i = overload(alt, i)

s = overload(shift, s)
e = overload(shift, e)

t = overload(control, t)
n = overload(control, n)

capslock = esc
' = enter
; = backspace
tab = overload(misc, tab)
leftmeta = overload(tab, leftmeta)
leftalt = layer(numpad)
rightalt = layer(symbols)

[numpad]
a = 1
r = 2
s = 3
t = 4
g = 5
m = 6
n = 7
e = 8
i = 9
o = 0
w = (
f = /
p = -
l = +
u = *
j = )
h = =

[symbols]
tab = ~
capslock = `
q = !
w = @
f = #
p = $
b = %
j = ^
l = &
u = *
y = (
; = )
a = <
r = [
s = {
t = (
g = "
m = '
n = )
e = }
i = ]
o = >
x = \
c = |
d = _
v = -

[misc]
m = left
n = down
e = up
i = right
j = prev
l = pagedown
u = pageup
; = next
; = playpause
k = volumedown
h = volumeup
, = brightnessdown
. = brightnessup
